language: go
go_import_path: github.com/howood/struct2struct
go:
  - 1.13.x

script:
  - go test -race -v ./...

env:
  global:
    - secure: 'AphEpJUpRl42M7ARNoeEZvK5+nPSPTl/iNiexqAiU4SWJHNjiYtasxcSx+uiu/mim9Ts3zQ2uFTU7ByLky5nzB+0F7g52qrw9Pb/YkOx4tcuj7yQhvgKILpot5pcL2WLnI6qsX9FGfxCF/tmAvpYbtDs6Cz++7gGVIUNc+nO4lTS2n+ifGB6xGc7pR09OTPZcF/1Wq3Umco9LL2sBimPoHFaQNG/arcNo4SMnhF0WtE6D/1r0QwbhxMt9QqIFNpnFyZMycTfEcCGbsKH3xi7CsZCi6dcttBBc58iOClce++7mU5egwduJiwgsDcsN1WLNlQoTwKm6POM477s9UGKcNnpNEyoMWi97BaXLz4lUez3EOew4V8QEZxecX3lTeBO/Cx7+R1hCwAbZtG1c3kaLvvQT3QxYT8CJlNvfg2FOURR/UyRDtwTznFeYIdJojD4o1Ey9OJxtbuM2r/+ZYS+eN+QjwHU/cIkxyrtQU9BoLyevJOQad2PykWefNIDU89IXoFjvm6/rzuiTEu5YTZ0Y+Yf/jNrkEA9vF2/YEIQyVxQPkaSIe44kx5CeXvKaQPm6bhJpby/cXgoVCDia2Kp20l7B29H1ZNX6lI0rszX9iPCYbDhrPEy/FBhB73ACiO//nAsRjpFOyDJe7X38++gGeBZUo5SP1VqMJi5PRDN52g='

after_success:
  - bundle exec codeclimate-test-reporter